name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # updates daily
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          filename: metrics.svg
          base: activity, community, repositories, metadata
          plugin_traffic: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_code: yes
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_starlists: yes
          plugin_habits: yes
          plugin_achievements: yes
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_filter: all
