name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours update
  workflow_dispatch:       # Allow manual run too

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
